apps/planificacion/urls.py
from django.conf.urls import url

from .viewstotal import cadenaproductiva as cadpro
from .viewstotal import divisionfuncional as divfun
from .viewstotal import ejeecon as ejeco
from .viewstotal import funcion, pdrc, pdrcobjetivo
from .viewstotal import grupofuncional as grufun
from .viewstotal import indicador as indic
from .viewstotal import metaffprogramado as mffp
from .viewstotal import metaffejecutado as mffe
from .viewstotal import periodo as peri
from .viewstotal import subactividadcomponente as subactcpte
from .viewstotal import accionestrategica as accest
from .viewstotal import productoproyecto as propry
from .viewstotal import pdrcobjetivoespecifico as pdrcobjesp
from .viewstotal import aexpop
from .viewstotal import accionobra as accobr
from .viewstotal import actividad
from .viewstotal import programapresupuestal as propres
from .viewstotal import actividadcatalogo as actcat
from .viewstotal import subactividadcatalogo as subactcat
from .viewstotal import tareacatalogo as tarcat
from .viewstotal.accionestrategicaXLSX import *
from .viewstotal.programapresupuestalXLSX import *
from .viewstotal.productoproyectoXLSX import *
from .viewstotal.periodoXLSX import *
from .viewstotal.ejeeconXLSX import *
from .viewstotal.pdrcXLSX import *
from .viewstotal.pdrcobjetivoXLSX import *
from .viewstotal.pdrcobjetivoespecificoXLSX import *
from .viewstotal.aexpopXLSX import *
from .viewstotal.divisionfuncionalXLSX import *
from .viewstotal.funcionXLSX import *
from .viewstotal.grupofuncionalXLSX import *
from .viewstotal.cadenaproductivaXLSX import *

urlpatterns = [

    # ESPECIALIDAD
    url(r'^periodo/$', peri.PeriodoView.as_view(), name='periodo_inicio'),
    url(r'^periodo/listar/$', peri.PeriodoListView.as_view(), name='periodo_listar'),
    url(r'^periodo/crear/$', peri.PeriodoCreateView.as_view(), name='periodo_crear'),
    url(r'^periodo/actualizar/(?P<pk>\d+)$', peri.PeriodoUpdateView.as_view(), name='periodo_actualizar'),
    url(r'^periodo/eliminar/(?P<pk>\d+)$', peri.PeriodoDeleteView.as_view(), name='periodo_eliminar'),
    url(r'^periodo/xlsx/$', ListaPeriodosXLSX, name='periodo_xlsx'),

    # GRUPO FUNCIONAL
    url(r'^grupofuncional/$', grufun.GrupoFuncionalView.as_view(), name='grupofuncional_inicio'),
    url(r'^grupofuncional/listar/$', grufun.GrupoFuncionalListView.as_view(), name='grupofuncional_listar'),
    url(r'^grupofuncional/crear/$', grufun.GrupoFuncionalCreateView.as_view(), name='grupofuncional_crear'),
    url(r'^grupofuncional/actualizar/(?P<pk>\d+)$', grufun.GrupoFuncionalUpdateView.as_view(), name='grupofuncional_actualizar'),
    url(r'^grupofuncional/eliminar/(?P<pk>\d+)$', grufun.GrupoFuncionalDeleteView.as_view(), name='grupofuncional_eliminar'),
    url(r'^grupofuncional/xlsx/$', ListaGrupoFuncionalXLSX, name='grupofuncional_xlsx'),

    # INDICADOR
    url(r'^indicador/$', indic.IndicadorView.as_view(), name='indicador_inicio'),
    url(r'^indicador/listar/$', indic.IndicadorListView.as_view(), name='indicador_listar'),
    url(r'^indicador/crear/$', indic.IndicadorCreateView.as_view(), name='indicador_crear'),
    url(r'^indicador/actualizar/(?P<pk>\d+)$', indic.IndicadorUpdateView.as_view(), name='indicador_actualizar'),
    url(r'^indicador/eliminar/(?P<pk>\d+)$', indic.IndicadorDeleteView.as_view(), name='indicador_eliminar'),

    # EJE ECONOMICO
    url(r'^ejeecon/$', ejeco.EjeEconView.as_view(), name='ejeecon_inicio'),
    url(r'^ejeecon/listar/$', ejeco.EjeEconListView.as_view(), name='ejeecon_listar'),
    url(r'^ejeecon/crear/$', ejeco.EjeEconCreateView.as_view(), name='ejeecon_crear'),
    url(r'^ejeecon/actualizar/(?P<pk>\d+)$', ejeco.EjeEconUpdateView.as_view(), name='ejeecon_actualizar'),
    url(r'^ejeecon/eliminar/(?P<pk>\d+)$', ejeco.EjeEconDeleteView.as_view(), name='ejeecon_eliminar'),
    url(r'^ejeecon/xlsx/$', ListaEjesXLSX, name='ejeecon_xlsx'),

    # CADENA PRODUCTIVA
    url(r'^cadenaproductiva/$', cadpro.CadenaProductivaView.as_view(), name='cadenaproductiva_inicio'),
    url(r'^cadenaproductiva/listar/$', cadpro.CadenaProductivaListView.as_view(), name='cadenaproductiva_listar'),
    url(r'^cadenaproductiva/crear/$', cadpro.CadenaProductivaCreateView.as_view(), name='cadenaproductiva_crear'),
    url(r'^cadenaproductiva/actualizar/(?P<pk>\d+)$', cadpro.CadenaProductivaUpdateView.as_view(), name='cadenaproductiva_actualizar'),
    url(r'^cadenaproductiva/eliminar/(?P<pk>\d+)$', cadpro.CadenaProductivaDeleteView.as_view(), name='cadenaproductiva_eliminar'),
    url(r'^cadenaproductiva/xlsx/$', CadenaProductivaXLSX, name='cadenaproductiva_xlsx'),

    # FUNCION
  	url(r'^funcion/$', funcion.FuncionView.as_view(), name='funcion_inicio'),
    url(r'^funcion/listar/$', funcion.FuncionListView.as_view(), name='funcion_listar'),
    url(r'^funcion/crear/$', funcion.FuncionCreateView.as_view(), name='funcion_crear'),
    url(r'^funcion/actualizar/(?P<pk>\d+)$', funcion.FuncionUpdateView.as_view(), name='funcion_actualizar'),
    url(r'^funcion/eliminar/(?P<pk>\d+)$', funcion.FuncionDeleteView.as_view(), name='funcion_eliminar'),
    url(r'^funcion/xlsx/$', ListaFuncionXLSX, name='funcion_xlsx'),

    # PDRC
  	url(r'^pdrc/$', pdrc.PdrcView.as_view(), name='pdrc_inicio'),
	url(r'^pdrc/listar/$', pdrc.PdrcListView.as_view(), name='pdrc_listar'),
	url(r'^pdrc/crear/$', pdrc.PdrcCreateView.as_view(), name='pdrc_crear'),
	url(r'^pdrc/actualizar/(?P<pk>\d+)$', pdrc.PdrcUpdateView.as_view(), name='pdrc_actualizar'),
    url(r'^pdrc/eliminar/(?P<pk>\d+)$', pdrc.PdrcDeleteView.as_view(), name='pdrc_eliminar'),
	url(r'^pdrc/xlsx/$', ListaPDRCsXLSX, name='pdrc_xlsx'),

    # DIVISION FUNCIONAL
    url(r'^divisionfuncional/$', divfun.DivisionFuncionalView.as_view(), name='divisionfuncional_inicio'),
    url(r'^divisionfuncional/listar/$', divfun.DivisionFuncionalListView.as_view(), name='divisionfuncional_listar'),
    url(r'^divisionfuncional/crear/$', divfun.DivisionFuncionalCreateView.as_view(), name='divisionfuncional_crear'),
    url(r'^divisionfuncional/actualizar/(?P<pk>\d+)$', divfun.DivisionFuncionalUpdateView.as_view(), name='divisionfuncional_actualizar'),
    url(r'^divisionfuncional/eliminar/(?P<pk>\d+)$', divfun.DivisionFuncionalDeleteView.as_view(), name='divisionfuncional_eliminar'),
    url(r'^divisionfuncional/xlsx/$', ListaDivisionFuncionaXLSX, name='divisionfuncional_xlsx'),

    # META FISICA FINANCIERA - programada
    url(r'^metaffprogramado/$', mffp.MetaFFPTipoView.as_view(), name='metaffprogramado_inicio'),
    url(r'^metaffprogramado/prodproy/$', mffp.MetaFFPProdProyView.as_view(), name='metaffprogramado_prodproy'),
    url(r'^metaffprogramado/accest/$', mffp.MetaFFPAccEstView.as_view(), name='metaffprogramado_accionestrategica'),
    url(r'^metaffprogramado/actividad/$', mffp.MetaFFPActividadView.as_view(), name='metaffprogramado_actividad'),
    url(r'^metaffprogramado/tabla/(?P<pk>\d+)$', mffp.MetaFFPTableView.as_view(), name='metaffprogramado_tabla'),
    url(r'^metaffprogramado/actualizarmeta/$', mffp.MetaFFPUpdateView, name='metaffprogramado_actualizar'),

    # META FISICA FINANCIERA - ejecutada
    url(r'^metaffejecutado/$', mffe.MetaFFETipoView.as_view(), name='metaffejecutado_inicio'),
    url(r'^metaffejecutado/prodproy/$', mffe.MetaFFEProdProyView.as_view(), name='metaffejecutado_prodproy'),
    url(r'^metaffejecutado/accest/$', mffe.MetaFFEAccEstView.as_view(), name='metaffejecutado_accionestrategica'),
    url(r'^metaffejecutado/actividad/$', mffe.MetaFFEActividadView.as_view(), name='metaffejecutado_actividad'),
    url(r'^metaffejecutado/tabla/(?P<pk>\d+)$', mffe.MetaFFETableView.as_view(), name='metaffejecutado_tabla'),
    url(r'^metaffejecutado/actualizarmeta/$', mffe.MetaFFEUpdateView, name='metaffejecutado_actualizar'),

    # SUB ACTIVIDAD COMPONENTE
    url(r'^subactividadcomponente/$', subactcpte.SubActividadComponenteProdProyView.as_view(), name='subactividadcomponente_inicio'),
    url(r'^subactividadcomponente/accest/$', subactcpte.SubActividadComponenteAccEstView.as_view(), name='subactividadcomponente_accionestrategica'),
    url(r'^subactividadcomponente/actividad/$', subactcpte.SubActividadComponenteActividadView.as_view(), name='subactividadcomponente_actividad'),
    url(r'^subactividadcomponente/tabla/(?P<pk>\d+)$', subactcpte.SubActividadComponenteTablaView.as_view(), name='subactividadcomponente_tabla'),
    url(r'^subactividadcomponente/listar/(?P<act>\d+)$', subactcpte.SubActividadComponenteListView.as_view(), name='subactividadcomponente_listar'),
    url(r'^subactividadcomponente/crear/$', subactcpte.SubActividadComponenteCreateView.as_view(), name='subactividadcomponente_crear'),
    url(r'^subactividadcomponente/actualizar/(?P<pk>\d+)$', subactcpte.SubActividadComponenteUpdateView.as_view(), name='subactividadcomponente_actualizar'),
    url(r'^subactividadcomponente/eliminar/(?P<pk>\d+)$', subactcpte.SubActividadComponenteDeleteView.as_view(), name='subactividadcomponente_eliminar'),

    # OBJETIVOS PDRC
    url(r'^pdrcobjetivo/$', pdrcobjetivo.PdrcObjetivoView.as_view(), name='pdrcobjetivo_inicio'),
    url(r'^pdrcobjetivo/listar/$', pdrcobjetivo.PdrcObjetivoListView.as_view(), name='pdrcobjetivo_listar'),
    url(r'^pdrcobjetivo/crear/$', pdrcobjetivo.PdrcObjetivoCreateView.as_view(), name='pdrcobjetivo_crear'),
    url(r'^pdrcobjetivo/actualizar/(?P<pk>\d+)$', pdrcobjetivo.PdrcObjetivoUpdateView.as_view(), name='pdrcobjetivo_actualizar'),
    url(r'^pdrcobjetivo/eliminar/(?P<pk>\d+)$', pdrcobjetivo.PdrcObjetivoDeleteView.as_view(), name='pdrcobjetivo_eliminar'),
    url(r'^pdrcobjetivo/xlsx/$', ListaObjetivoPdrcXLSX, name='pdrcobjetivo_xlsx'),

    # OBJETIVOS ESPECIFICOS
    url(r'^pdrcobjesp/$', pdrcobjesp.ObjetivoEspecificoPdrcView.as_view(), name='objetivoespecifico_inicio'),
    url(r'^pdrcobjesp/pdrc/obj$', pdrcobjesp.ObjetivoEspecificoObjPdrcView.as_view(), name='objetivoespecifico_objpdrc'),

sisagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'', login_required(TemplateView.as_view(template_name='inicio/login.html')), name='login_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.inicio.urls", namespace='home_base')),
    url(r'^inicio/', include("apps.inicio.urls", namespace='inicio')),
    url(r'^administracion/', include("apps.administracion.urls", namespace='administracion')),
    url(r'^planificacion/', include("apps.planificacion.urls", namespace='planificacion')),
    url(r'^agricola/', include("apps.agricola.urls", namespace='agricola')),
    url(r'^reportes/', include("apps.reportes.urls", namespace='reportes')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/planificacion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/planificacion/templates/planificacion/metaffejecutado/accionestrategica.html
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/select2/django_select2.js' %}"></script>
<form method='GET' id="formAccEst" action="{% url 'planificacion:metaffejecutado_actividad' %}">
    {% csrf_token %}
    {{ formAccEst }}
</form>
<div id="dataActividad">
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#formAccEst").ajaxForm({ target: "#dataActividad" });
    });
    $(".formAccEst_load").on("change", function() {
        formAccEst_load();
    });
    function formAccEst_load() {
        if ($("#cb_accest").val() > 0) {
            $("#formAccEst").submit();
        }
    }
</script>

apps/planificacion/templates/planificacion/metaffejecutado/actividad.html
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/select2/django_select2.js' %}"></script>
<form method='GET' id="formActividad">
    {% csrf_token %}
    {{ formActividad }}
</form>
<div id="dataMetaFF">
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#formActividad").ajaxForm({ target: "#dataMetaFF" });
    });
    $(".formActividad_load").on("change", function() {
        formActividad_load();
    });
    function formActividad_load() {
        if ($("#cb_actividad").val() > 0) {
            url_MFF = "{% url 'planificacion:metaffejecutado_tabla' 0 %}";
            url_MFF = url_MFF.replace("/0", "/" + $("#cb_actividad").val());
            $("#formActividad").prop("action", url_MFF).submit();
        }
    }
</script>

apps/planificacion/templates/planificacion/metaffejecutado/productoproyecto.html
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/select2/django_select2.js' %}"></script>
<form method='GET' id="formProdProy" action="{% url 'planificacion:metaffejecutado_accionestrategica' %}">
    {% csrf_token %}
    {{ formProdProy }}
</form>
<div id="dataAccEst">
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#formProdProy").ajaxForm({ target: "#dataAccEst" });
    });
    $(".formProdProy_load").on("change", function() {
        formProdProy_load();
    });
    function formProdProy_load() {
        if ($("#cb_prodproy").val() > 0) {
            $("#formProdProy").submit();
        }
    }
</script>

apps/planificacion/templates/planificacion/metaffejecutado/table.html
{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'js/bootstrap3-editable/css/bootstrap-editable.css' %}">
<script type="text/javascript" src="{% static 'js/bootstrap3-editable/js/bootstrap-editable.min.js' %}"></script>
<script type="text/javascript">
    $.fn.editable.defaults.ajaxOptions={headers:{"X-CSRFToken":"{{ csrf_token }}"}, type:'post', dataType:'json'};
    $.fn.editable.defaults.mode="inline";
    $.fn.editable.defaults.anim="1000";
</script>
<form method="POST" id="formMetaFF">
    <table class="table table-responsive table-bordered table-striped table-hover table-condensed">
        <caption>Programación de Metas Físicas/Financieras</caption>
        <thead>
            <tr>
                <th class="text-center">PROGRAMACIÓN</th>
                <th class="text-center" colspan="2">FÍSICO (%)</th>
                <th class="text-center" colspan="2">FINANCIERO (S/)</th>
            </tr>
            <tr>
                <th class="text-center">MES</th>
                <th class="text-center">Programado</th>
                <th class="text-center">Ejecutado</th>
                <th class="text-center">Programado</th>
                <th class="text-center">Ejecutado</th>
            </tr>
        </thead>
        <tbody>
            {% for metaff in oMetasff %}
                <tr>
                    <td class="col-sm-4">
                        {{ metaff.mes.nombre }}
                    </td>
                    <td class="col-sm-2 text-center">
                        {{ metaff.metafisica_programada|default:0 }}
                    </td>
                    <td class="col-sm-2 text-center">
                        <a href="#" id="valor" class="editable_field" data-type="number" data-pk="{{ metaff.pk }}"
                           data-url="{% url 'planificacion:metaffejecutado_actualizar' %}" data-title="Meta Física" data-params={tipo:"fis"}
                           data-min="0" data-max="{{ metaff.metafisica_programada|default:0|floatformat:2 }}">
                           {{ metaff.metafisica_ejecutada|default:0 }}
                        </a>
                    </td>
                    <td class="col-sm-2 text-center">
                        {{ metaff.metafinanciera_programada|default:0|floatformat:2 }}
                    </td>
                    <td class="col-sm-2 text-center">
                        <a href="#" id="valor" class="editable_field" data-type="number" data-pk="{{ metaff.pk }}"
                           data-url="{% url 'planificacion:metaffejecutado_actualizar' %}" data-title="Meta Financiera" data-params={tipo:"fin"}
                           data-min="0" data-max="{{ metaff.metafinanciera_programada|default:0|floatformat:2 }}" data-step="0.01">
                           {{ metaff.metafinanciera_ejecutada|default:0|floatformat:2 }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
<script type="text/javascript">
    $('.editable_field').editable();
</script>

apps/planificacion/templates/planificacion/metaffejecutado/tipo.html
{% extends "base_drac.html" %}
{% load static from staticfiles %}

{% block maestro_titulo %}
{% endblock maestro_titulo %}

{% block maestro_contenido %}
    <form method='GET' id="formTipo" action="{% url 'planificacion:metaffejecutado_prodproy' %}">
        {% csrf_token %}
        {{ formTipo }}
    </form>
    <div id="dataProdProy">
    </div>
{% endblock maestro_contenido %}

{% block maestro_scripts %}
    <script type="text/javascript">
        $(".formTipo_load").on("change", function() {
            formTipo_load();
        });
        function formTipo_load() {
            $("#formTipo").submit();
        }
        $(document).ready(function() {
            $("#formTipo").ajaxForm({ target: "#dataProdProy" });
            formTipo_load();
        });
    </script>
{% endblock maestro_scripts %}