apps/agricola/urls.py
from django.conf.urls import url
from .viewstotal import socio as soc
from .viewstotal import enfermedad, base
from .viewstotal import variedadcatalogo as varicat
from .viewstotal import empresaCompras as empresa
from .viewstotal import variedad as vari
from .viewstotal import plaga as plaga
from .viewstotal import especie as espe
from .viewstotal import raza
from .viewstotal import razasocio
from .viewstotal import tareacpcu
from .viewstotal import tareacpcr
from .viewstotal.enfermedadXLSX import *
from .viewstotal.baseXLSX import *
from .viewstotal.variedadXLSX import *
from .viewstotal.variedadsocioXLSX import *
from .viewstotal.socioXLSX import *

urlpatterns = [
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),

    # SOCIO
    url(r'^socio/$', soc.SocioSelectView.as_view(), name='socio_inicio'),
    url(r'^socio/tabla/(?P<pk>\d+)$', soc.SocioView.as_view(), name='socio_tabla'),
    url(r'^socio/listar/(?P<base>\d+)$', soc.SocioListView.as_view(), name='socio_listar'),
    url(r'^socio/crear/$', soc.SocioCreateView.as_view(), name='socio_crear'),
    url(r'^socio/actualizar/(?P<pk>\d+)$', soc.SocioUpdateView.as_view(), name='socio_actualizar'),
    url(r'^socio/eliminar/(?P<pk>\d+)$', soc.SocioDeleteView.as_view(), name='socio_eliminar'),
    url(r'^socio/xlsx/(?P<inicio>\d{2}-\d{2}-\d{4})/(?P<fin>\d{2}-\d{2}-\d{4})/$', ListaSociosXLS, name='socio_xlsx'),

    # ENFERMEDAD
    url(r'^enfermedad/$', enfermedad.EnfermedadView.as_view(), name='enfermedad_inicio'),
    url(r'^enfermedad/listar/$', enfermedad.EnfermedadListView.as_view(), name='enfermedad_listar'),
    url(r'^enfermedad/crear/$', enfermedad.EnfermedadCreateView.as_view(), name='enfermedad_crear'),
    url(r'^enfermedad/actualizar/(?P<pk>\d+)$', enfermedad.EnfermedadUpdateView.as_view(), name='enfermedad_actualizar'),
    url(r'^enfermedad/eliminar/(?P<pk>\d+)$', enfermedad.EnfermedadDeleteView.as_view(), name='enfermedad_eliminar'),
    url(r'^enfermedad/xlsx/$', ListaEnfermedadesXLS, name='enfermedad_xlsx'),
    # BASE
    url(r'^base/$', base.BaseView.as_view(), name='base_inicio'),
    url(r'^base/listar/$', base.BaseListView.as_view(), name='base_listar'),
    url(r'^base/crear/$', base.BaseCreateView.as_view(), name='base_crear'),
    url(r'^base/actualizar/(?P<pk>\d+)$', base.BaseUpdateView.as_view(), name='base_actualizar'),
    url(r'^base/eliminar/(?P<pk>\d+)$', base.BaseDeleteView.as_view(), name='base_eliminar'),
    url(r'^base/xlsx/$', ListaBasesXLS, name='base_xlsx'),

    # VARIEDAD
    url(r'^variedad/$', vari.VariedadBaseView.as_view(), name='variedad_inicio'),
    url(r'^variedad/socio/$', vari.VariedadSocioView.as_view(), name='variedad_socio'),
    url(r'^variedad/tabla/(?P<pk>\d+)$', vari.VariedadTablaView.as_view(), name='variedad_tabla'),
    url(r'^variedad/listar/(?P<socid>\d+)$', vari.VariedadListView.as_view(), name='variedad_listar'),
    url(r'^variedad/crear/$', vari.VariedadCreateView.as_view(), name='variedad_crear'),
    url(r'^variedad/actualizar/(?P<pk>\d+)$', vari.VariedadUpdateView.as_view(), name='variedad_actualizar'),
    url(r'^variedad/eliminar/(?P<pk>\d+)$', vari.VariedadDeleteView.as_view(), name='variedad_eliminar'),
    url(r'^variedad/xlsx/(?P<tipocertificacion>[\w\-]+)/(?P<provincia>\d+)/(?P<distrito>\d+)/(?P<centropoblado>\d+)/(?P<caserio>\d+)/$', ListaVariedadesXLS, name='variedad_xlsx'),
    url(r'^variedad/socio/(?P<idsocio>\d+)/xlsx/$', ListaVariedadSocioXLS, name='variedad_socio_xlsx'),

    # PLAGA
    url(r'^plaga/$', plaga.PlagaView.as_view(), name='plaga_inicio'),
    url(r'^plaga/listar/$', plaga.PlagaListView.as_view(), name='plaga_listar'),
    url(r'^plaga/crear/$', plaga.PlagaCreateView.as_view(), name='plaga_crear'),
    url(r'^plaga/actualizar/(?P<pk>\d+)$', plaga.PlagaUpdateView.as_view(), name='plaga_actualizar'),
    url(r'^plaga/eliminar/(?P<pk>\d+)$', plaga.PlagaDeleteView.as_view(), name='plaga_eliminar'),

    # ESPECIE
    url(r'^especie/$', espe.EspecieView.as_view(), name='especie_inicio'),
    url(r'^especie/listar/$', espe.EspecieListView.as_view(), name='especie_listar'),
    url(r'^especie/crear/$', espe.EspecieCreateView.as_view(), name='especie_crear'),
    url(r'^especie/actualizar/(?P<pk>\d+)$', espe.EspecieUpdateView.as_view(), name='especie_actualizar'),
    url(r'^especie/eliminar/(?P<pk>\d+)$', espe.EspecieDeleteView.as_view(), name='especie_eliminar'),
    url(r'^especie/(?P<pk>\d+)/enfermedades$', espe.EspecieEnfermedadesView.as_view(), name='especie_enfermedades'),
    # url(r'^especie/enfermedades/actualizar/(?P<pk>\d+)$', espe.EspecieEnfermedadesUpdateView.as_view(), name='especie_enfermedades_actualizar'),

    # RAZA
    url(r'^raza/$', raza.RazaSelectView.as_view(), name='raza_inicio'),
    url(r'^raza/tabla/(?P<pk>\d+)$', raza.RazaTableView.as_view(), name='raza_tabla'),
    url(r'^raza/listar/(?P<especie>\d+)$', raza.RazaListView.as_view(), name='raza_listar'),
    url(r'^raza/crear/$', raza.RazaCreateView.as_view(), name='raza_crear'),
    url(r'^raza/actualizar/(?P<pk>\d+)$', raza.RazaUpdateView.as_view(), name='raza_actualizar'),
    url(r'^raza/eliminar/(?P<pk>\d+)$', raza.RazaDeleteView.as_view(), name='raza_eliminar'),

    # RAZASOCIO
    url(r'^razasocio/$', razasocio.RazaSocioView.as_view(), name='razasocio_inicio'),
    url(r'^razasocio/listar/$', razasocio.RazaSocioListView.as_view(), name='razasocio_listar'),
    url(r'^razasocio/crear/$', razasocio.RazaSocioCreateView.as_view(), name='razasocio_crear'),
    url(r'^razasocio/actualizar/(?P<pk>\d+)$', razasocio.RazaSocioUpdateView.as_view(), name='razasocio_actualizar'),
    url(r'^razasocio/eliminar/(?P<pk>\d+)$', razasocio.RazaSocioDeleteView.as_view(), name='razasocio_eliminar'),
    url(r'^razasocio/socio/(?P<pk>\d+)$', razasocio.RazaSocioDetailView.as_view(), name='razasocio_detailview'),

    # TAREAS CULTIVOS
    url(r'^tareacpcu/$', tareacpcu.TareaCpCuCadProdView.as_view(), name='tareacpcu_inicio'),
    url(r'^tareacpcu/act/$', tareacpcu.TareaCpCuActividadView.as_view(), name='tareacpcu_actividad'),
    url(r'^tareacpcu/subact/$', tareacpcu.TareaCpCuSubActividadView.as_view(), name='tareacpcu_subactividad'),
    url(r'^tareacpcu/tabla/(?P<pk>\d+)$', tareacpcu.TareaCpCuTablaView.as_view(), name='tareacpcu_tabla'),
    url(r'^tareacpcu/listar/(?P<subact>\d+)$', tareacpcu.TareaCpCuListView.as_view(), name='tareacpcu_listar'),
    url(r'^tareacpcu/crear/$', tareacpcu.TareaCpCuCreateView.as_view(), name='tareacpcu_crear'),
    url(r'^tareacpcu/actualizar/(?P<pk>\d+)$', tareacpcu.TareaCpCuUpdateView.as_view(), name='tareacpcu_actualizar'),
    url(r'^tareacpcu/eliminar/(?P<pk>\d+)$', tareacpcu.TareaCpCuDeleteView.as_view(), name='tareacpcu_eliminar'),

    # TAREAS CRIANZA
    url(r'^tareacpcr/$', tareacpcr.TareaCpCrView.as_view(), name='tareacpcr_inicio'),
    url(r'^tareacpcr/listar/$', tareacpcr.TareaCpCrListView.as_view(), name='tareacpcr_listar'),
    url(r'^tareacpcr/crear/$', tareacpcr.TareaCpCrCreateView.as_view(), name='tareacpcr_crear'),
    url(r'^tareacpcr/actualizar/(?P<pk>\d+)$', tareacpcr.TareaCpCrUpdateView.as_view(), name='tareacpcr_actualizar'),
    url(r'^tareacpcr/eliminar/(?P<pk>\d+)$', tareacpcr.TareaCpCrDeleteView.as_view(), name='tareacpcr_eliminar'),

    # CATALOGO DE VARIEDADES
    url(r'^variedadcatalogo/$', varicat.VariedadCatalogoView.as_view(), name='variedadcatalogo_inicio'),
    url(r'^variedadcatalogo/listar/$', varicat.VariedadCatalogoListView.as_view(), name='variedadcatalogo_listar'),
    url(r'^variedadcatalogo/crear/$', varicat.VariedadCatalogoCreateView.as_view(), name='variedadcatalogo_crear'),
    url(r'^variedadcatalogo/actualizar/(?P<pk>\d+)$', varicat.VariedadCatalogoUpdateView.as_view(), name='variedadcatalogo_actualizar'),
    url(r'^variedadcatalogo/eliminar/(?P<pk>\d+)$', varicat.VariedadCatalogoDeleteView.as_view(), name='variedadcatalogo_eliminar'),


    # ENPRESA COMPRA
    url(r'^empresa/$', empresa.EmpresaTableView.as_view(), name='empresa_inicio'),
    url(r'^empresa/listar/$', empresa.EmpresaListView .as_view(), name='empresa_listar'),
    url(r'^empresa/crear/$', empresa.EmpresaCreateView.as_view(), name='empresa_crear'),
    url(r'^empresa/actualizar/(?P<pk>\d+)$', empresa.EmpresaUpdateView.as_view(), name='empresa_actualizar'),
    url(r'^empresa/eliminar/(?P<pk>\d+)$', empresa.EmpresaDeleteView.as_view(), name='empresa_eliminar'),

    # url(r'^persona/$', empresa.PersonaView.as_view(), name='persona_inicio'),
    # url(r'^persona/listar/$', empresa.PersonaListView.as_view(), name='persona_listar'),
    # url(r'^persona/crear/$', empresa.PersonaCreateView.as_view(), name='persona_crear'),
    # url(r'^persona/actualizar/(?P<pk>\d+)$', empresa.PersonaUpdateView.as_view(), name='persona_actualizar'),
    # url(r'^persona/eliminar/(?P<pk>\d+)$', empresa.PersonaDeleteView.as_view(), name='persona_eliminar'),

]

apps/inicio/urls.py
from django.conf.urls import url
from .viewstotal import inicio
from .viewstotal import login
from .viewstotal import unidadmedida as uni
from .viewstotal import profesion as prof
from .viewstotal import especialidad as esp
from .viewstotal import tipoorganizacion as tiporg
from .viewstotal import mes
from .viewstotal import centropoblado as cenpo
from .viewstotal import caserio
from .viewstotal.profesionXLSX import *
from .viewstotal.tipoorganizacionXLSX import *

urlpatterns = [

	# LOGIN
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),
    url(r'^$', inicio.InicioView, name="inicio_view"),
    url(r'^login$', login.LoginView, name='user_login'),
    url(r'^logout$', login.LogoutView, name='user_logout'),

	# UNIDAD MEDIDA
    url(r'^unidadmedida/$', uni.UnidadMedidaView.as_view(), name='unidadmedida_inicio'),
    url(r'^unidadmedida/listar/$', uni.UnidadMedidaListView.as_view(), name='unidadmedida_listar'),
    url(r'^unidadmedida/crear/$', uni.UnidadMedidaCreateView.as_view(), name='unidadmedida_crear'),
    url(r'^unidadmedida/actualizar/(?P<pk>\d+)$', uni.UnidadMedidaUpdateView.as_view(), name='unidadmedida_actualizar'),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', uni.UnidadMedidaDeleteView.as_view(), name='unidadmedida_eliminar'),


    # PROFESION
    url(r'^profesion/listar/$', prof.ProfesionTemplateView.as_view(), name='profesion_inicio'),
    url(r'^profesion/listar/json$', prof.ListarProfesionJson.as_view(), name='profesion_listar'),
    url(r'^profesion/(?P<pk>\d+)/crear/$', prof.ProfesionCreateView.as_view(), name='profesion_create'),
    url(r'^profesion/(?P<pk>\d+)/eliminar/$', prof.ProfesionDeleteView.as_view(), name='profesion_delete'),
    url(r'^profesion/xlsx/$', ListaProfesionesXLS, name='profesion_xlsx'),

    # ESPECIALIDAD
    url(r'^especialidad/$', esp.EspecialidadView.as_view(), name='especialidad_inicio'),
    url(r'^especialidad/listar/$', esp.EspecialidadListView.as_view(), name='especialidad_listar'),
    url(r'^especialidad/crear/$', esp.EspecialidadCreateView.as_view(), name='especialidad_crear'),
    url(r'^especialidad/actualizar/(?P<pk>\d+)$', esp.EspecialidadUpdateView.as_view(), name='especialidad_actualizar'),
    url(r'^especialidad/eliminar/(?P<pk>\d+)$', esp.EspecialidadDeleteView.as_view(), name='especialidad_eliminar'),


    # MES
    url(r'^mes/$', mes.MesTemplateView.as_view(), name='mes_inicio'),
    url(r'^mes/listar/$', mes.ListarMesJson.as_view(), name='mes_listar'),
    url(r'^mes/(?P<pk>\d+)/crear/$', mes.MesCreateView.as_view(), name='profesion_create'),
    url(r'^mes/(?P<pk>\d+)/eliminar/$', mes.MesDeleteView.as_view(), name='profesion_eliminar'),

    # TIPO ORGANIZACION
    url(r'^tipoorganizacion/$', tiporg.TipoOrganizacionView.as_view(), name='tipoorganizacion_inicio'),
    url(r'^tipoorganizacion/listar/$', tiporg.TipoOrganizacionListView.as_view(), name='tipoorganizacion_listar'),
    url(r'^tipoorganizacion/crear/$', tiporg.TipoOrganizacionCreateView.as_view(), name='tipoorganizacion_crear'),
    url(r'^tipoorganizacion/actualizar/(?P<pk>\d+)$', tiporg.TipoOrganizacionUpdateView.as_view(), name='tipoorganizacion_actualizar'),
    url(r'^tipoorganizacion/eliminar/(?P<pk>\d+)$', tiporg.TipoOrganizacionDeleteView.as_view(), name='tipoorganizacion_eliminar'),
    url(r'^tipoorganizacion/xlsx/$', ListaTipoOrganizacionXLSX, name='tipoorganizacion_xlsx'),

    # CENTRO POBLADO
    url(r'^centropoblado/$', cenpo.CentroPobladoTemplateView.as_view(), name='centropoblado_inicio'),
    url(r'^centropoblado/listar/$', cenpo.CentroPobladoListView.as_view(), name='centropoblado_lista'),
    url(r'^centropoblado/crear/(?P<dist>\d+)$', cenpo.CentroPobladoCreateView.as_view(), name='centropoblado_crear'),
    url(r'^centropoblado/actualizar/(?P<pk>\d+)$', cenpo.CentroPobladoUpdateView.as_view(), name='centropoblado_actualizar'),
    url(r'^centropoblado/eliminar/(?P<pk>\d+)$', cenpo.CentroPobladoDeleteView.as_view(), name='centropoblado_eliminar'),
    url(r'^centropoblado/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', cenpo.ProvincaDistritoListView.as_view(), name='centropoblado_ubiego'),

    # CASERIO
    url(r'^caserio/$', caserio.CaserioTemplateView.as_view(), name='caserio_inicio'),
    url(r'^caserio/listar/$', caserio.CaserioListView.as_view(), name='caserio_lista'),
    url(r'^caserio/crear/(?P<cp>\d+)$', caserio.CaserioCreateView.as_view(), name='caserio_crear'),
    url(r'^caserio/actualizar/(?P<pk>\d+)$', caserio.CaserioUpdateView.as_view(), name='caserio_actualizar'),
    url(r'^caserio/eliminar/(?P<pk>\d+)$', caserio.CaserioDeleteView.as_view(), name='caserio_eliminar'),
    url(r'^caserio/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', caserio.ProvincaDistritoListView.as_view(), name='caserio_ubiego'),



]

sisagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'', login_required(TemplateView.as_view(template_name='inicio/login.html')), name='login_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.inicio.urls", namespace='home_base')),
    url(r'^inicio/', include("apps.inicio.urls", namespace='inicio')),
    url(r'^administracion/', include("apps.administracion.urls", namespace='administracion')),
    url(r'^planificacion/', include("apps.planificacion.urls", namespace='planificacion')),
    url(r'^agricola/', include("apps.agricola.urls", namespace='agricola')),
    url(r'^reportes/', include("apps.reportes.urls", namespace='reportes')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/agricola/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/inicio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/agricola/templates/agricola/socio/eliminar.html
{% extends "base_form.html" %}
{% block form_body %}
    <form id="formSocio" method='POST' class="form" role="form">
        {% csrf_token %}
        {% if delete_error != None %}
            <div class="text-danger form-group">
                Error!!: {{ delete_error|escape }}
            </div>
        {% endif %}
        {{ object.persona.nombreCompleto }}
        {% if object.telefono|length > 0 %}<br/>{{ object.telefono }}{% endif %}
        {% if object.email|length > 0 %}<br/>{{ object.email }}{% endif %}
        <br/>{{ object.base }}
    </form>
    <script>
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView = $('#formSocio');
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

apps/agricola/templates/agricola/socio/formulario.html
{% extends "base_form.html" %}
{% block form_body %}
    <form method='POST' id="formSocio" >
        {% csrf_token %}
        {% for field in form %}
            {% if field.is_hidden %}
                {{ field.as_hidden }}
            {% else %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label" style="{% if field.field.required == True %}font-weight: bold;{% endif %}">{{ field.label}}:</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                    {% for error in field.errors  %}
                    <div class="col-sm-10 col-sm-offset-2" >
                        <label id="{{ field.id_for_label }}_label"for="{{ field.id_for_label }}" class="text-danger">
                            {{ error|escape }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endfor %}
    </form>
    <script type="text/javascript">
        $formView = $('#formSocio');
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

apps/agricola/templates/agricola/socio/inicio.html
{% extends "base_drac.html" %}
{% load static from staticfiles %}

{% block maestro_titulo %}
{% endblock maestro_titulo %}

{% block maestro_contenido %}
    <form method='GET' id="formBase">
        {% csrf_token %}
        {{ formBase }}
    </form>
    <div id="dataSOCIO">
    </div>
{% endblock maestro_contenido %}

{% block maestro_scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#formBase").ajaxForm({ target: "#dataSOCIO" });
        });
        $(".formBase_load").on("change", function() {
            formBase_load();
        });
        function formBase_load() {
            if ($("#cb_base").val() > 0) {
                urlSocios = "{% url 'agricola:socio_tabla' 0 %}";
                urlSocios = urlSocios.replace("/0", "/" + $("#cb_base").val());
                $("#formBase").prop("action", urlSocios).submit();
            }
        }
    </script>
{% endblock maestro_scripts %}

apps/agricola/templates/agricola/socio/socio.html
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'js/bootstrap-table.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-table-fixed-columns.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap-table-es-SP.min.js' %}"></script>
<div id="toolbar">
    <button id="btnNuevo" type="button" class="btn btn-default" >
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </button>
</div>
<table id="tablaSocio"
    data-toolbar="#toolbar"
    data-toggle="table"
    data-url="{% url 'agricola:socio_listar' oBase.pk %}">
    <thead>
    <tr>
        <th data-field="persona" data-sortable="true" data-switchable="true" class="col-md-5">Nombre</th>
        <th data-field="ingreso" data-sortable="true" data-switchable="true" class="col-md-2">Ingreso</th>
        <th data-field="email" data-sortable="true" data-switchable="true" class="col-md-2">Email</th>
        <th data-field="telefono" data-sortable="true" data-switchable="true" class="col-md-2">Telefono</th>
        <th data-field="action" data-formatter="actionFormatter" data-switchable="false" data-events="actionEvents"
            class="col-md-1" data-align="center">Acciones</th>
    </tr>
    </thead>
</table>
<div id="modalSocio" class="modal fade" data-keyboard="true" data-backdrop="true" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button id="btnGuardar" type="button" class="btn btn-primary">Guardar Cambios</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Exportar</h4>
      </div>
      <div class="modal-body">
          <div class="row">
            <p>
                <form method="Post">
                  <div class="form-group col-xs-12 col-sm-6">
                    <label for="f_inicio">Inicio:</label>
                    <input type="text" name="inicio" id="f_inicio" data-datepicker-type="4" required="" data-provide="datepicker-inline" class="form-control datepicker">
                    <p class="help-text">
                        Ejemplo: 01-01-2017
                    </p>
                  </div>
                  <div class="form-group col-xs-12 col-sm-6">
                    <label for="f_fin">Fin:</label>
                    <input type="text" name="fin" id="f_fin" data-datepicker-type="4" required="" data-provide="datepicker-inline" class="form-control datepicker">
                    <p class="help-text">
                        Ejemplo: 01-01-2017
                    </p>
                  </div>
                  <div class="col-xs-12 text-right">
                    <button id="btnExcel" type="button" class="btn btn-default">Exportar</button>    
                  </div>
                </form>
            </p>  
          </div>
      </div>
      <!-- div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div -->
    </div>

  </div>
</div>

<script src="{% static 'js/listagrilla.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    url_crear = "{% url 'agricola:socio_crear' %}";
    url_eliminar = "{% url 'agricola:socio_eliminar' 0 %}";
    url_eliminar = url_eliminar.substr(0, url_eliminar.length-1);
    url_editar = "{% url 'agricola:socio_actualizar' 0 %}";
    url_editar = url_editar.substr(0, url_editar.length-1);
    //
    $formTitulo = "Socio";
    $formGenero = "o";
    $modalForm = $("#modalSocio");
    $tablaView = $("#tablaSocio");
    $formView = null;
    $firstField = 'tb_base';
    opcion = "";
    idValue = 0;
    url_post = null;
    //
    $modalFormLoaded = "scLoadedForm();";
    function scLoadedForm() {
        setTimeout(function() {
            $("#id_baseid").val($("#cb_base").val());
        }, 200);
    }
</script>