apps/administracion/urls.py
from django.conf.urls import url

from .viewstotal import funcioncargo as funcar
from .viewstotal import area
from .viewstotal import usuario as usu
from .viewstotal import persona, trabajador
from .viewstotal import organizacion as org
from .viewstotal.personaXLSX import *
from .viewstotal.areaXLSX import *
from .viewstotal.funcioncargoXLSX import *
from .viewstotal.organizacionXLSX import *

urlpatterns = [
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),

	# FUNCION / CARGO
    url(r'^funcioncargo/$', funcar.FuncionCargoView.as_view(), name='funcioncargo_inicio'),
    url(r'^funcioncargo/listar/$', funcar.FuncionCargoListView.as_view(), name='funcioncargo_listar'),
    url(r'^funcioncargo/crear/$', funcar.FuncionCargoCreateView.as_view(), name='funcioncargo_crear'),
    url(r'^funcioncargo/actualizar/(?P<pk>\d+)$', funcar.FuncionCargoUpdateView.as_view(), name='funcioncargo_actualizar'),
    url(r'^funcioncargo/eliminar/(?P<pk>\d+)$', funcar.FuncionCargoDeleteView.as_view(), name='funcioncargo_eliminar'),
    url(r'^funcioncargo/xlsx/$', ListaFuncionCargoXLSX, name='funcioncargo_xlsx'),

  	# AREA
  	url(r'^area/$', area.AreaView.as_view(), name='area_inicio'),
    url(r'^area/listar/$', area.AreaListView.as_view(), name='area_listar'),
    url(r'^area/crear/$', area.AreaCreateView.as_view(), name='area_crear'),
    url(r'^area/actualizar/(?P<pk>\d+)$', area.AreaUpdateView.as_view(), name='area_actualizar'),
    url(r'^area/eliminar/(?P<pk>\d+)$', area.AreaDeleteView.as_view(), name='area_eliminar'),
    url(r'^area/xlsx/$', ListaAreasXLSX, name='area_xlsx'),

    # USUARIO
    url(r'^usuario/$', usu.UsuarioView.as_view(), name='usuario_inicio'),
    url(r'^usuario/listar$', usu.UsuarioListView.as_view(), name='usuario_listar'),
    url(r'^usuario/crear$', usu.UsuarioCreateView.as_view(), name='usuario_crear'),
    url(r'^usuario/actualizar/(?P<pk>\d+)$', usu.UsuarioUpdateView.as_view(), name='usuario_actualizar'),
    url(r'^usuario/eliminar/(?P<pk>\d+)$', usu.UsuarioDeleteView.as_view(), name='usuario_eliminar'),
    url(r'^usuario/persona/listar$', usu.UsuarioPersonaListView.as_view(), name='usuario_persona_listar'),
    url(r'^usuario/permisos/(?P<pk>\d+)$', usu.UsuarioPermisosView.as_view(), name='usuario_permisos'),
    url(r'^usuario/cambiarpassword$', usu.UsuarioCambiarPasswordView, name='usuario_cambiarpassword'),

    # PERSONA
    url(r'^persona/$', persona.PersonaView.as_view(), name='persona_inicio'),
    url(r'^persona/listar/$', persona.PersonaListView.as_view(), name='persona_listar'),
    url(r'^persona/crear/$', persona.PersonaCreateView.as_view(), name='persona_crear'),
    url(r'^persona/actualizar/(?P<pk>\d+)$', persona.PersonaUpdateView.as_view(), name='persona_actualizar'),
    url(r'^persona/eliminar/(?P<pk>\d+)$', persona.PersonaDeleteView.as_view(), name='persona_eliminar'),
    url(r'^persona/xlsx/$', ListaPersonasXLSX, name='persona_xlsx'),

    # TRABAJADOR
    url(r'^trabajador/$', trabajador.TrabajadorView.as_view(), name='trabajador_inicio'),
    url(r'^trabajador/listar/$', trabajador.TrabajadorListView.as_view(), name='trabajador_listar'),
    url(r'^trabajador/crear/$', trabajador.TrabajadorCreateView.as_view(), name='trabajador_crear'),
    url(r'^trabajador/actualizar/(?P<pk>\d+)$', trabajador.TrabajadorUpdateView.as_view(), name='trabajador_actualizar'),
    url(r'^trabajador/eliminar/(?P<pk>\d+)$', trabajador.TrabajadorDeleteView.as_view(), name='trabajador_eliminar'),

    # ORGANIZACION
  	url(r'^organizacion/$', org.OrganizacionTemplateView.as_view(), name='organizacion_inicio'),
	url(r'^organizacion/listar/$', org.OrganizacionListView.as_view(), name='organizacion_listar'),
	url(r'^organizacion/crear/$', org.OrganizacionCreateView.as_view(), name='organizacion_crear'),
	url(r'^organizacion/actualizar/(?P<pk>\d+)$', org.OrganizacionUpdateView.as_view(), name='organizacion_actualizar'),
	url(r'^organizacion/eliminar/(?P<pk>\d+)$', org.OrganizacionDeleteView.as_view(), name='organizacion_eliminar'),
    url(r'^organizacion/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', org.UbiegoCaserioListView.as_view(), name='caserio_ubiego'),
    url(r'^organizacion/xlsx/(?P<provincia>\d+)/(?P<distrito>\d+)/(?P<centropoblado>\d+)/$', ListaOrganizacionesCargoXLSX, name='caserio_ubiego'),

]

apps/inicio/urls.py
from django.conf.urls import url
from .viewstotal import inicio
from .viewstotal import login
from .viewstotal import unidadmedida as uni
from .viewstotal import profesion as prof
from .viewstotal import especialidad as esp
from .viewstotal import tipoorganizacion as tiporg
from .viewstotal import mes
from .viewstotal import centropoblado as cenpo
from .viewstotal import caserio
from .viewstotal.profesionXLSX import *
from .viewstotal.tipoorganizacionXLSX import *

urlpatterns = [

	# LOGIN
    # url(r'^modelo/accion/$', ModeloAccion, name='modelo_accion'),
    url(r'^$', inicio.InicioView, name="inicio_view"),
    url(r'^login$', login.LoginView, name='user_login'),
    url(r'^logout$', login.LogoutView, name='user_logout'),

	# UNIDAD MEDIDA
    url(r'^unidadmedida/$', uni.UnidadMedidaView.as_view(), name='unidadmedida_inicio'),
    url(r'^unidadmedida/listar/$', uni.UnidadMedidaListView.as_view(), name='unidadmedida_listar'),
    url(r'^unidadmedida/crear/$', uni.UnidadMedidaCreateView.as_view(), name='unidadmedida_crear'),
    url(r'^unidadmedida/actualizar/(?P<pk>\d+)$', uni.UnidadMedidaUpdateView.as_view(), name='unidadmedida_actualizar'),
    url(r'^unidadmedida/eliminar/(?P<pk>\d+)$', uni.UnidadMedidaDeleteView.as_view(), name='unidadmedida_eliminar'),


    # PROFESION
    url(r'^profesion/listar/$', prof.ProfesionTemplateView.as_view(), name='profesion_inicio'),
    url(r'^profesion/listar/json$', prof.ListarProfesionJson.as_view(), name='profesion_listar'),
    url(r'^profesion/(?P<pk>\d+)/crear/$', prof.ProfesionCreateView.as_view(), name='profesion_create'),
    url(r'^profesion/(?P<pk>\d+)/eliminar/$', prof.ProfesionDeleteView.as_view(), name='profesion_delete'),
    url(r'^profesion/xlsx/$', ListaProfesionesXLS, name='profesion_xlsx'),

    # ESPECIALIDAD
    url(r'^especialidad/$', esp.EspecialidadView.as_view(), name='especialidad_inicio'),
    url(r'^especialidad/listar/$', esp.EspecialidadListView.as_view(), name='especialidad_listar'),
    url(r'^especialidad/crear/$', esp.EspecialidadCreateView.as_view(), name='especialidad_crear'),
    url(r'^especialidad/actualizar/(?P<pk>\d+)$', esp.EspecialidadUpdateView.as_view(), name='especialidad_actualizar'),
    url(r'^especialidad/eliminar/(?P<pk>\d+)$', esp.EspecialidadDeleteView.as_view(), name='especialidad_eliminar'),


    # MES
    url(r'^mes/$', mes.MesTemplateView.as_view(), name='mes_inicio'),
    url(r'^mes/listar/$', mes.ListarMesJson.as_view(), name='mes_listar'),
    url(r'^mes/(?P<pk>\d+)/crear/$', mes.MesCreateView.as_view(), name='profesion_create'),
    url(r'^mes/(?P<pk>\d+)/eliminar/$', mes.MesDeleteView.as_view(), name='profesion_eliminar'),

    # TIPO ORGANIZACION
    url(r'^tipoorganizacion/$', tiporg.TipoOrganizacionView.as_view(), name='tipoorganizacion_inicio'),
    url(r'^tipoorganizacion/listar/$', tiporg.TipoOrganizacionListView.as_view(), name='tipoorganizacion_listar'),
    url(r'^tipoorganizacion/crear/$', tiporg.TipoOrganizacionCreateView.as_view(), name='tipoorganizacion_crear'),
    url(r'^tipoorganizacion/actualizar/(?P<pk>\d+)$', tiporg.TipoOrganizacionUpdateView.as_view(), name='tipoorganizacion_actualizar'),
    url(r'^tipoorganizacion/eliminar/(?P<pk>\d+)$', tiporg.TipoOrganizacionDeleteView.as_view(), name='tipoorganizacion_eliminar'),
    url(r'^tipoorganizacion/xlsx/$', ListaTipoOrganizacionXLSX, name='tipoorganizacion_xlsx'),

    # CENTRO POBLADO
    url(r'^centropoblado/$', cenpo.CentroPobladoTemplateView.as_view(), name='centropoblado_inicio'),
    url(r'^centropoblado/listar/$', cenpo.CentroPobladoListView.as_view(), name='centropoblado_lista'),
    url(r'^centropoblado/crear/(?P<dist>\d+)$', cenpo.CentroPobladoCreateView.as_view(), name='centropoblado_crear'),
    url(r'^centropoblado/actualizar/(?P<pk>\d+)$', cenpo.CentroPobladoUpdateView.as_view(), name='centropoblado_actualizar'),
    url(r'^centropoblado/eliminar/(?P<pk>\d+)$', cenpo.CentroPobladoDeleteView.as_view(), name='centropoblado_eliminar'),
    url(r'^centropoblado/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', cenpo.ProvincaDistritoListView.as_view(), name='centropoblado_ubiego'),

    # CASERIO
    url(r'^caserio/$', caserio.CaserioTemplateView.as_view(), name='caserio_inicio'),
    url(r'^caserio/listar/$', caserio.CaserioListView.as_view(), name='caserio_lista'),
    url(r'^caserio/crear/(?P<cp>\d+)$', caserio.CaserioCreateView.as_view(), name='caserio_crear'),
    url(r'^caserio/actualizar/(?P<pk>\d+)$', caserio.CaserioUpdateView.as_view(), name='caserio_actualizar'),
    url(r'^caserio/eliminar/(?P<pk>\d+)$', caserio.CaserioDeleteView.as_view(), name='caserio_eliminar'),
    url(r'^caserio/ubigeo/(?P<pk>\d+)/(?P<valor>\d+)/$', caserio.ProvincaDistritoListView.as_view(), name='caserio_ubiego'),



]

sisagro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # url(r'', login_required(TemplateView.as_view(template_name='inicio/login.html')), name='login_user'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("apps.inicio.urls", namespace='home_base')),
    url(r'^inicio/', include("apps.inicio.urls", namespace='inicio')),
    url(r'^administracion/', include("apps.administracion.urls", namespace='administracion')),
    url(r'^planificacion/', include("apps.planificacion.urls", namespace='planificacion')),
    url(r'^agricola/', include("apps.agricola.urls", namespace='agricola')),
    url(r'^reportes/', include("apps.reportes.urls", namespace='reportes')),
    url(r'^select2/', include('django_select2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administracion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.db import models
from ..inicio.models import Auditoria, Especialidad, Profesion, Provincia, Caserio, TipoOrganizacion
from ..inicio.funciones import CalcularEdad
from django.contrib.auth.models import User

# Create your models here.
class FuncionCargo(Auditoria):
    nombre = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'Función - Cargo'
        verbose_name_plural = 'Funciones - Cargos'

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return ""

class Area(Auditoria):
    nombre = models.CharField(max_length=150, unique=True)
    abreviatura = models.CharField(max_length=10, unique=True)
    estado = models.BooleanField(default=True)
    esagencia = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Areas'

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return ""

class Organizacion(Auditoria):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    ruc = models.CharField(max_length=45, unique=True)
    area = models.DecimalField(max_digits=9, decimal_places=2)
    rendimiento = models.DecimalField(max_digits=9, decimal_places=2)
    volumen = models.DecimalField(max_digits=9, decimal_places=2)
    caserio = models.ForeignKey(Caserio, on_delete=models.PROTECT)
    tipoorganizacion = models.ForeignKey(TipoOrganizacion, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Organización'
        verbose_name_plural = 'Organizaciones'

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return ""

class Persona(Auditoria):
    SexoM = 'M'
    SexoF = 'F'

    Sexos_Opciones = (
        (SexoM, u'Masculino'),
        (SexoF, u'Femenino')
    )

    dni = models.CharField(max_length=8, unique=True)
    nombres = models.CharField(max_length=50)
    apepat = models.CharField(max_length=50)
    apemat = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, default=SexoM, choices=Sexos_Opciones)
    fechanacimiento = models.DateField()
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'

    def __unicode__(self):
        return self.nombreCompleto()

    def get_absolute_url(self):
        return ""

    def estrabajador(self):
        _result = False
        for tra in self.trabajador_set.all():
            if tra.fechafin == None:
                _result = True
                break
        return _result

    def nombreCompleto(self):
        return self.nombres + ' ' + self.apepat + ' ' + self.apemat

    def Sexo(self):
        _result = ""
        for op in self.Sexos_Opciones:
            if op[0] == self.sexo:
                _result = op[1]
                break
        return _result

    def EdadActual(self):
        return CalcularEdad(self.fechanacimiento, datetime.datetime.now().date())

class Trabajador(Auditoria):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)
    area = models.ForeignKey(Area, on_delete=models.PROTECT)
    funcioncargo = models.ForeignKey(FuncionCargo, on_delete=models.PROTECT)
    especialidad = models.ForeignKey(Especialidad, on_delete=models.PROTECT)
    profesion = models.ForeignKey(Profesion, on_delete=models.PROTECT)
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    direccion = models.CharField(max_length=45, blank=True)
    modalidad = models.CharField(max_length=45, blank=True)
    fechainicio = models.DateField()
    fechafin = models.DateField(blank=True, null=True)
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Trabajador'
        verbose_name_plural = 'Trabajadores'

    def __unicode__(self):
        return self.persona.nombreCompleto()

    def get_absolute_url(self):
        return ""

class Menu(Auditoria):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    ruta = models.CharField(max_length=100, blank=True, null=True)
    padre = models.ForeignKey('self', blank=True, null=True, related_name='menupadre', on_delete=models.PROTECT)
    orden = models.IntegerField(default=0)
    estado = models.BooleanField(default=True)
    separador = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Menú'
        verbose_name_plural = 'Menús'

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return ""

    def Descripcion(self):
        return self.descripcion if self.descripcion != None and len(self.descripcion) > 0 else self.nombre

class Acceso(Auditoria):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)
    menu = models.ForeignKey(Menu, on_delete=models.PROTECT)

    class Meta:
        verbose_name = 'Acceso'
        verbose_name_plural = 'Accesos'

    def __unicode__(self):
        return self.persona.nombreCompleto()

    def get_absolute_url(self):
        return ""

apps/administracion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/inicio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

apps/administracion/templates/administracion/usuario/cambiarpassword.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">
        Cambiar Contraseña
    </h4>
</div>
<div class="modal-body">
    {% if change_ok != None %}
        <label for="" class="text-success">
            {{ change_ok }}
        </label>
    {% else %}
        <form id="f_changepassword" method="post" action="{% url 'administracion:usuario_cambiarpassword' %}">
            {% csrf_token %}
            {{ form }}
        </form>
    {% endif %}
</div>
<div class="modal-footer">
    {% if change_ok == None %}
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button id="btnChgPwd" type="button" class="btn btn-primary">Actualizar</button>
    {% else %}
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
    {% endif %}
</div>
{% if change_ok == None %}
    <script type="text/javascript">
        $fChgPwd = $("#f_changepassword");
        $("#btnChgPwd").on("click", function() {
            $fChgPwd.waitMe({text: "Procesando... Un momento por favor!!!"});
            $fChgPwd.submit();
        });
        var fChgPwdOptions = {
            target: $("#modalUser .modal-content"),
            success: function(res, status, xhr, form) {
            }
        };
        $fChgPwd.ajaxForm(fChgPwdOptions);
        $( document ).ready(function() {
            $("#id_old_password").focus();
        });
    </script>
{% endif %}

apps/administracion/templates/administracion/usuario/eliminar.html
{% extends "base_form.html" %}
{% block form_body %}
    <form id="formUsuario" method='POST' class="form" role="form">
        {% csrf_token %}
        {% if delete_error != None %}
            <div class="text-danger form-group">
                Error!!: {{ delete_error|escape }}
            </div>
        {% endif %}
        {{ object.username }}<br />
        {{ object.persona.nombreCompleto }}<br />
    </form>
    <script>
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView = $('#formUsuario');
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

apps/administracion/templates/administracion/usuario/formulario.html
{% extends "base_form.html" %}
{% block form_body %}
    <form method='POST' id="formUsuario" >
        {% csrf_token %}
        {% for field in form %}
            {% if field.name != "id_persona" %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label" style="{% if field.field.required == True %}font-weight: bold;{% endif %}">{{ field.label}}:</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                    {% for error in field.errors  %}
                    <div class="col-sm-10 col-sm-offset-2" >
                        <label id="{{ field.id_for_label }}_label"for="{{ field.id_for_label }}" class="text-danger">
                            {{ error|escape }}
                        </label>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endfor %}
    </form>
    <script>
        $formView = $('#formUsuario');
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}

apps/administracion/templates/administracion/usuario/inicio.html
{% extends "base_drac.html" %}
{% load static from staticfiles %}

{% block maestro_estilos %}
{% endblock maestro_estilos %}

{% block maestro_contenido %}
    <div id="toolbar">
        <button id="btnNuevo" type="button" class="btn btn-default" >
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
	</div>
	<table id="tablaUsuario"
		data-toolbar="#toolbar"
		data-toggle="table"
		data-url="{% url 'administracion:usuario_listar' %}">
	    <thead>
	        <tr>
            	<th data-field="username" data-sortable="true" data-switchable="true" class="col-md-4">Nombre</th>
            	<th data-field="persona" data-sortable="true" data-switchable="true" class="col-md-5">Persona</th>
            	<th data-field="is_superuser" data-sortable="true" data-switchable="true" class="col-md-1">Admin</th>
            	<th data-field="is_active" data-sortable="true" data-switchable="true" class="col-md-1">Estado</th>
            	<th data-field="action" data-formatter="actionFormatter" data-switchable="false"
                    data-events="actionEvents" class="col-md-1" data-align="center">Acciones</th>
	        </tr>
	    </thead>
	</table>
    <div id="modalUsuario" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"></h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button id="btnGuardar" type="button" class="btn btn-primary">Guardar Cambios</button>
          </div>
        </div>
      </div>
    </div>
{% endblock maestro_contenido %}

{% block maestro_scripts %}
    <script type="text/javascript">
        url_crear = "{% url 'administracion:usuario_crear' %}";
        url_eliminar = "{% url 'administracion:usuario_eliminar' 0 %}";
        url_eliminar = url_eliminar.substr(0, url_eliminar.length-1);
        url_editar = "{% url 'administracion:usuario_actualizar' 0 %}";
        url_editar = url_editar.substr(0, url_editar.length-1);
        url_permisos = "{% url 'administracion:usuario_permisos' 0 %}";
        url_permisos = url_permisos.substr(0, url_permisos.length-1);
        //
        $formTitulo = "Usuario";
        $formGenero = "o";
        $modalForm = $("#modalUsuario");
        $tablaView = $("#tablaUsuario");
        $formView = null;
        $firstField = "id_username";
        opcion = "";
        idValue = 0;
        url_post = null;
    </script>
    <script src="{% static 'js/administracion/usuario/listagrilla.js' %}" type="text/javascript"></script>
{% endblock maestro_scripts %}

apps/administracion/templates/administracion/usuario/permisos.html
{% extends "base_form.html" %}
{% block form_body %}
    <form method='POST' id="formPermisos">
        {% csrf_token %}
        <ul class="nav nav-tabs">
            {% for opcion in opciones %}
                <li {% if forloop.first %}class="active"{% endif %}>
                    <a data-toggle="tab" href="#tab_op_{{ opcion.id }}">
                        {{ opcion.nombre }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="tab-content">
            {% for opcion in opciones %}
                <div id="tab_op_{{ opcion.id }}" class="tab-pane fade {% if forloop.first %}in active{% endif %}" style="padding: 5px">
                    {% for menu in menus %}
                        {% if menu.padre == opcion.id %}
                            <div class="form-group">
                                <input name="acc_{{ menu.id }}" type="checkbox" {% if menu.estado %}checked{% endif %}>
                                {{ menu.nombre }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </form>
    <script>
        $formView = $('#formPermisos');
        var form_options = {
            target: $modalForm,
            success: function() {
            }
        }
        $formView.ajaxForm(form_options);
    </script>
{% endblock form_body %}